### ISSUE TITLE
Are spaces in paths supported?

### ISSUE THREAD

**Issue by Fauntleroy** [mklabs/node-fileset#11]
The documentation mentions that you can check multiple patterns like so:

```javascript
fileset('**.coffee README.md *.json Cakefile **.js', 'node_modules/**')
```

Is there any way to use this library with paths that have spaces in them? I've tried surrounding the path in quotes... `"/bravado site/views/**/*.hbs"` to no avail.

**Comment by mklabs** [comment]
Thanks @Fauntleroy and @vmeurisse
