### ISSUE TITLE
Update test suite

### ISSUE THREAD

**Issue by mklabs** [mklabs/node-fileset#26]
Test suite no longer pass. fileset needs an update in its test suite to make it pass again.

**Comment by JJ** [comment]
OK; I'll check this out. :-)

**Comment by ntwb** [comment]
The build passed on Travis CI and is all green for the 5 NodeJS versions tested?

https://travis-ci.org/mklabs/node-fileset/builds/140202443

**Comment by mklabs** [comment]
True, thank you @ntwb

**Comment by mklabs** [comment]
As for the version to bump, any advice ? Should it be a major version as per semver ?

**Comment by mklabs** [comment]
I'm working on releasing a new major version, I hope that's ok.

Thanks to both of you.

**Comment by ntwb** [comment]
A new `major` version will be fine, `2.0.0` would be that version 👍
